ros2_api:
  ros__parameters:
    states_topic: "/joint_states" 
    publishers: 
      - publisher: "JointGroupVelocityController"
        name: "velocity"  
        topic: "/vel_cmds"   
    transport:
      type: "protocols::UnixDomainSocket"
      params:
        socket_path_recv: "/tmp/test_sdk.socket"
        socket_path_send: "/tmp/test_ros2.socket"
