validator_node:
  ros__parameters:
# Workspace boundaries (for walls).
    workspace:
      use_workspace: true
      min_x: -1.5
      max_x: 1.5
      min_y: -1.5
      max_y: 1.5
      min_z: -1.5
      max_z: 1.5
    # Additional collision objects.
    collision_objects:
      names: ["box1", "box2"]
      # Each object must have x, y, z, depth, height, and width parameters.
      box1:
        x: -0.6
        y: 0.0
        z: 0.25
        depth: 0.5
        height: 0.5
        width: 0.5
      box2:
        x: 2.0
        y: 1.0
        z: 0.5
        depth: 1.0
        height: 0.25
        width: 0.25
    