validator_node:
  ros__parameters:
    workspace:
      use_workspace: true
      min_x: -1.0
      max_x: 1.0
      min_y: -1.0
      max_y: 1.0
      min_z: -0.1
      max_z: 1.5
    collision_objects:
      names: ["box1"]
      box1:
        x: -2.6
        y: 1.0
        z: 1.25
        depth: 0.5
        height: 0.5
        width: 0.5