# Default initial positions for robco's ros2_control fake system

initial_positions:
  drive1_joint: -1.323
  drive2_joint: 0.2
  drive3_joint: 0.7
  drive4_joint: 0.3
  drive5_joint: 1.5
  drive6_joint: -0.4