<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robco">
  <xacro:property name="description_package" value="$(find robco_description)" />
  <xacro:macro name="handeye"
    params="connected_to:='' ns:='' rpy:='0 0 0' xyz:='0 0 0' safety_distance:=0">
    <xacro:unless value="${not connected_to}">
      <joint name="${ns}_handeye_joint" type="fixed">
        <parent link="${connected_to}" />
        <child link="${ns}_handeye" />
        <origin xyz="${xyz}" rpy="${rpy}" />
      </joint>
    </xacro:unless>

    <link name="${ns}_handeye">
      <visual>
        <geometry>
          <mesh filename="file://${description_package}/meshes/handeye/d415_mount.stl" />
        </geometry>
        <material name="Gray">
          <color rgba="0.9 0.9 0.9 1.0" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0.006" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${0.038+safety_distance}" length="0.012" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0.0375 0 0.0055" rpy="0 0 0" />
        <geometry>
          <box size="${0.075+safety_distance} ${0.03+safety_distance} ${0.012+safety_distance}" />
        </geometry>
      </collision>
    </link>

    <joint name="${ns}_handeye_flange_joint" type="fixed">
      <parent link="${ns}_handeye" />
      <child link="${ns}_handeye_flange" />
      <origin xyz="0 0 0.012" rpy="0 0 0" />
    </joint>

    <link name="${ns}_handeye_flange"></link>
  </xacro:macro>
</robot>