# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
  
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController


joint_group_velocity_controller:
  ros__parameters:
    joints:
      - drive1_joint
      - drive2_joint
      - drive3_joint
      - drive4_joint
      - drive5_joint
      - drive6_joint

      