# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    type: velocity_controllers/JointTrajectoryController
    joints:
      - drive1_joint
      - drive2_joint
      - drive3_joint
      - drive4_joint
      - drive5_joint
      - drive6_joint

    gains:
      drive1_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
      drive2_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
      drive3_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
      drive4_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
      drive5_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
      drive6_joint: {p: 100, d: 1, i: 1, i_clamp: 1}